name: PR Build

on:
  pull_request:
    branches:
      - master

jobs:
  deskpro_app_test_and_build:
    name: Test / Build
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --no-tags --depth=1 origin master

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm tsc --noemit

      - name: Run tests
        run: pnpm test:coverage

      - name: Get labels from pull request
        id: labels
        run: echo "milestone=$(jq --raw-output '.pull_request.labels[].name' $GITHUB_EVENT_PATH | grep -E 'major-version|minor-version' | head -1)" >> $GITHUB_OUTPUT

      - name: Bump Version
        run: |
          git config --global user.name "git log -1 --pretty=format:%an"
          git config --global user.email "$(git log -1 --pretty=format:%ae)"
          if [ "$(git log -1 --pretty=format:%ae)" = "noreply@github.com" ]; then
            echo "Skipping workflow run because previous commit was not made by workflow."
            exit 0
          fi
          if [[ "${{ steps.labels.outputs.milestone }}" == "major-version" ]]; then
            pnpm run bumpManifestVer major
          elif [[ "${{ steps.labels.outputs.milestone }}" == "minor-version" ]]; then
            pnpm run bumpManifestVer minor
          else
            pnpm run bumpManifestVer
          fi

      - name: Build
        run: pnpm run build
      - name: Package app zip
        working-directory: dist
        run: |
          zip -rq ../app.zip *
          mv ../app.zip .
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: |
            dist/app.zip
            dist/manifest.json
          retention-days: 1

  deploy:
    uses: DeskproApps/app-template-vite/.github/workflows/subworkflow-deploy.yml@master
    secrets: inherit
    if: github.actor != 'dependabot[bot]'
    needs: [deskpro_app_test_and_build]
